package org.una.loaders;

/**
 *
 * @author Esteban Vargas
 */
public enum Permisos {
    ARCHIVO_RELACIONADO_CREAR("AR1"),
    ARCHIVO_RELACIONADO_MODIFICAR("AR2"),
    ARCHIVO_RELACIONADO_CONSULTAR("AR3"),
    ARCHIVO_RELACIONADO_CONSULTAR_TODO("AR4"),
    ARCHIVO_RELACIONADO_ELIMINAR("AR5"), 
    ARCHIVO_RELACIONADO_ELIMINAR_TODO("AR6"),
    
    CLIENTE_CREAR("CLIE1"),
    CLIENTE_MODIFICAR("CLIE2"),
    CLIENTE_CONSULTAR("CLIE3"),
    CLIENTE_CONSULTAR_TODO("CLIE4"),
    CLIENTE_ELIMINAR("CLIE5"), 
    CLIENTE_ELIMINAR_TODO("CLIE6"),
    
    NOTA_CREAR("NOT1"),
    NOTA_MODIFICAR("NOT2"),
    NOTA_CONSULTAR("NOT3"),
    NOTA_CONSULTAR_TODO("NOT4"),
    NOTA_ELIMINAR("NOT5"), 
    NOTA_ELIMINAR_TODO("NOT6"),
    
    PARAMETRO_GENERAL_CREAR("PG1"),
    PARAMETRO_GENERAL_MODIFICAR("PG2"),
    PARAMETRO_GENERAL_CONSULTAR("PG3"),
    PARAMETRO_GENERAL_CONSULTAR_TODO("PG4"),
    PARAMETRO_GENERAL_ELIMINAR("PG5"), 
    PARAMETRO_GENERAL_ELIMINAR_TODO("PG6"),
    
    PERMISO_CREAR("PE1"),
    PERMISO_MODIFICAR("PE2"),
    PERMISO_CONSULTAR("PE3"),
    PERMISO_CONSULTAR_TODO("PE4"),
    PERMISO_ELIMINAR("PE5"), 
    PERMISO_ELIMINAR_TODO("PE6"),
    
    PERMISO_OTORGADO_CREAR("PEO1"),
    PERMISO_OTORGADO_MODIFICAR("PEO2"),
    PERMISO_OTORGADO_CONSULTAR("PEO3"),
    PERMISO_OTORGADO_CONSULTAR_TODO("PEO4"),
    PERMISO_OTORGADO_ELIMINAR("PEO5"), 
    PERMISO_OTORGADO_ELIMINAR_TODO("PEO6"),
    
    REQUISITO_CREAR("RE1"),
    REQUISITO_MODIFICAR("RE2"),
    REQUISITO_CONSULTAR("RE3"),
    REQUISITO_CONSULTAR_TODO("RE4"),
    REQUISITO_ELIMINAR("RE5"), 
    REQUISITO_ELIMINAR_TODO("RE6"),
    
    REQUISITO_PRESENTADO_CREAR("REP1"),
    REQUISITO_PRESENTADO_MODIFICAR("REP2"),
    REQUISITO_PRESENTADO_CONSULTAR("REP3"),
    REQUISITO_PRESENTADO_CONSULTAR_TODO("REP4"),
    REQUISITO_PRESENTADO_ELIMINAR("REP5"), 
    REQUISITO_PRESENTADO_ELIMINAR_TODO("REP6"),
   
    TRANSACCION_CREAR("TRA1"),
    TRANSACCION_CONSULTAR("TRA2"),
    TRANSACCION_CONSULTAR_TODO("TRA3"),
    
    VARIACION_CREAR("VA1"),
    VARIACION_MODIFICAR("VA2"),
    VARIACION_CONSULTAR("VA3"),
    VARIACION_CONSULTAR_TODO("VA4"),
    VARIACION_ELIMINAR("VA5"), 
    VARIACION_ELIMINAR_TODO("VA6"),
    
    USUARIO_CREAR("USU1"),
    USUARIO_MODIFICAR("USU2"),
    USUARIO_INACTIVAR("USU3"),
    USUARIO_CONSULTAR("USU4"),
    USUARIO_CONSULTAR_TODO("USU5"),
    USUARIO_ELIMINAR("USU6"), 
    USUARIO_ELIMINAR_TODO("USU7"),
    
    DEPARTAMENTO_CREAR("DEP1"),
    DEPARTAMENTO_MODIFICAR("DEP2"),
    DEPARTAMENTO_INACTIVAR("DEP3"),
    DEPARTAMENTO_CONSULTAR("DEP4"),
    DEPARTAMENTO_ELIMINAR("DEP5"), 
    DEPARTAMENTO_ELIMINAR_TODO("DEP6"),
    DEPARTAMENTO_CONSULTAR_TODO("DEP7"),
    
    TRAMITE_REGISTRAR("TRA1"),
    TRAMITE_MODIFICAR("TRA2"),
    TRAMITE_INACTIVAR("TRA3"),
    TRAMITE_FINALIZAR("TRA4"),
    TRAMITE_CONSULTAR("TRA5"),
    TRAMITE_CONSULTAR_TODO("TRA6"),
    TRAMITE_DISEÑAR("TRD1"),
    
    TRANSACCION_CONSULTAR_REPORTE("TRU1"),
    ALERTA_CONSULTAR("TRU2"),
    
    TRAMITE_PROPIO_REGISTRAR("TAG1"),
    TRAMITE_PROPIO_CONSULTAR("TAG2"),
    TRAMITE_USUARIO_CONSULTAR("REP1"),
    TRAMITE_FECHA_CONSULTAR("REP2"),
    TRAMITE_TIPO_CONSULTAR("REP3"),
    TRAMITE_ESTADO_CONSULTAR("REP4"),
    TRAMITE_DEPARTAMENTO_CONSULTAR("REP5"),
    TRAMITE_CLIENTE_CONSULTAR("REP6");

    private String codigo;

    Permisos(String codigo) {
        this.codigo = codigo;
    }

    public String getCodigo() {
        return codigo;
    }

}
